name = "wenpay"
main = "src/index.ts"
compatibility_date = "2023-03-15"

[[d1_databases]]
binding = "DB"
database_name = "wenpay"
database_id = "da75e2fb-1ea7-4bac-b4ea-f8d859db253e"

# The necessary secrets are:
# - PRIVATE_KEY
# Run `echo <VALUE> | wrangler secret put <NAME>` for each of these
